### ISSUE TITLE
Support PyTorch=1.5 

### ISSUE THREAD

**Issue by sidml** [Jia-Research-Lab/PointGroup#4]
Hi.
Currently the pointgroup library doesn't compile correctly in Pytorch 1.5.
I get the following errors when i try to compile

> In file included from src/pointgroup_ops.cpp:8:0:
src/bfs_cluster/bfs_cluster.cpp:32:58: error: ‘THCState_getCurrentStream’ was not declared in this scope

> src/bfs_cluster/bfs_cluster.cpp:9:80: error: ‘AT_CHECK’ was not declared in this scope

These two errors can be easily solved and the pointgroup library can be made compatible with PyTorch 1.5. In [bfs_cluster.cpp](https://github.com/Jia-Research-Lab/PointGroup/blob/master/lib/pointgroup_ops/src/bfs_cluster/bfs_cluster.cpp) following changes need to be made:
1.  Replace THCState_getCurrentStream with at::cuda::getCurrentCUDAStream().
https://stackoverflow.com/questions/55919123/cuda-for-pytorch-cuda-c-stream-and-state
2.  Replace AT_CHECK with TORCH_CHECK.

With the above mentioned changes, i was able to compile Pointgroup library with PyTorch 1.5, and Cuda 10.2.
Thanks.

**Comment by llijiang** [comment]
Thanks!
I have made some corresponding [changes](https://github.com/Jia-Research-Lab/PointGroup/commit/a41c2cd22808861f0d4986b2825875c10bb661e5) in 'pointgroup_ops' to make it compatible with Pytorch 1.5.

**Comment by fuy34** [comment]
Hi @sidml 

May I ask how did you resolve the compatibility issues on spconv part? I am using the same environment with you (PyTorch 1.5 + cuda 10.2), but I cannot compile spconv in the first stage. And for pointgroup_ops, the new commit from @llijiang leads to a ```ImportError: libcudart.so.10.0```. I guess it is still not compatible with CUDA-10.2. 

I am digging into the details, but please let me know if you have already solved it. Thank you in advance. 

===============================

For people who will meet the same problem, [here](https://github.com/Jia-Research-Lab/PointGroup/issues/25#issuecomment-720892712) is my solution.

**Comment by onurtore** [comment]
Torch 1.5 has a problem with the nonzero function, the call for ballquery_batch_p gives an error due to the nonzero call.

`/pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
        nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
        nonzero(Tensor input, *, bool as_tuple)
CUDA kernel failed : invalid configuration argument
`

Does anyone have a similar problem?
